In [22]:
import pandas as pd
import numpy as np

In [28]:
df1 = pd.read_excel('data_academic_performance.xlsx')
df1.head()

,COD_S11,GENDER,EDU_FATHER,EDU_MOTHER,OCC_FATHER,OCC_MOTHER,STRATUM,SISBEN,PEOPLE_HOUSE,Unnamed: 9,...,CC_PRO,ENG_PRO,WC_PRO,FEP_PRO,G_SC,PERCENTILE,2ND_DECILE,QUARTILE,SEL,SEL_IHE
0,SB11201210000129,F,Incomplete Professional Education,Complete technique or technology,Technical or professional level employee,Home,Stratum 4,It is not classified by the SISBEN,Three,NaN,...,71,93,79,181,180,91,5,4,2,2
1,SB11201210000137,F,Complete Secundary,Complete professional education,Entrepreneur,Independent professional,Stratum 5,It is not classified by the SISBEN,Three,NaN,...,86,98,78,201,182,92,5,4,4,4
2,SB11201210005154,M,Not sure,Not sure,Independent,Home,Stratum 2,Level 2,Five,NaN,...,18,43,22,113,113,7,1,1,1,1
3,SB11201210007504,F,Not sure,Not sure,Other occupation,Independent,Stratum 2,It is not classified by the SISBEN,Three,NaN,...,76,80,48,137,157,67,4,3,2,2
4,SB11201210007548,M,Complete professional education,Complete professional education,Executive,Home,Stratum 4,It is not classified by the SISBEN,One,NaN,...,98,100,71,189,198,98,5,4,4,2

In [3]:
display(df)

,COD_S11,GENDER,EDU_FATHER,EDU_MOTHER,OCC_FATHER,OCC_MOTHER,STRATUM,SISBEN,PEOPLE_HOUSE,Unnamed: 9,...,CC_PRO,ENG_PRO,WC_PRO,FEP_PRO,G_SC,PERCENTILE,2ND_DECILE,QUARTILE,SEL,SEL_IHE
0,SB11201210000129,F,Incomplete Professional Education,Complete technique or technology,Technical or professional level employee,Home,Stratum 4,It is not classified by the SISBEN,Three,NaN,...,71,93,79,181,180,91,5,4,2,2
1,SB11201210000137,F,Complete Secundary,Complete professional education,Entrepreneur,Independent professional,Stratum 5,It is not classified by the SISBEN,Three,NaN,...,86,98,78,201,182,92,5,4,4,4
2,SB11201210005154,M,Not sure,Not sure,Independent,Home,Stratum 2,Level 2,Five,NaN,...,18,43,22,113,113,7,1,1,1,1
3,SB11201210007504,F,Not sure,Not sure,Other occupation,Independent,Stratum 2,It is not classified by the SISBEN,Three,NaN,...,76,80,48,137,157,67,4,3,2,2
4,SB11201210007548,M,Complete professional education,Complete professional education,Executive,Home,Stratum 4,It is not classified by the SISBEN,One,NaN,...,98,100,71,189,198,98,5,4,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12406,SB11201420568705,M,Ninguno,Complete Secundary,Other occupation,Auxiliary or Administrative,Stratum 2,It is not classified by the SISBEN,Six,NaN,...,86,87,65,142,176,88,5,4,2,2
12407,SB11201420573045,M,Complete professional education,Complete Secundary,Executive,Other occupation,Stratum 2,Level 2,Five,NaN,...,44,11,0,127,107,4,1,1,4,2
12408,SB11201420578809,M,Complete technique or technology,Complete technique or technology,Retired,Home,Stratum 2,Level 2,Five,NaN,...,90,81,87,192,188,95,5,4,2,2
12409,SB11201420578812,F,Complete professional education,Complete professional education,Independent professional,Small entrepreneur,Stratum 3,It is not classified by the SISBEN,Seven,NaN,...,51,8,42,121,146,50,3,3,3,2
12410,SB11201420583232,M,Complete Secundary,Complete primary,Independent,Home,Stratum 3,Level 1,Four,NaN,...,91,79,47,193,178,89,5,4,2,4

In [20]:
import pymysql
# Establish a connection to the MySQL server
connection = pymysql.connect(
    host="localhost",
    user="root",
    password="Driti@2003",
    database="student_data"
)
# Create a cursor object to execute SQL queries
cursor = connection.cursor()

show_tables = "SHOW TABLES"
cursor.execute(show_tables)
# Fetch all tables
tables = cursor.fetchall()

# Display the list of tables
print("Tables in the database:")
for table in tables:
    print(table[0])

Tables in the database:
data_academic_performance

In [19]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.0-py3-none-any.whl (44 kB)
     -------------------------------------- 44.8/44.8 kB 276.2 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.0

In [23]:
cursor.execute('SELECT * FROM data_academic_performance')

table_rows = cursor.fetchall()

df = pd.DataFrame(table_rows)

In [24]:
display(df)

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,SB11201210000129,F,Incomplete Professional Education,Complete technique or technology,Technical or professional level employee,Home,Stratum 4,It is not classified by the SISBEN,Three,,...,71,93,79,181,180,91,5,4,2,2
1,SB11201210000137,F,Complete Secundary,Complete professional education,Entrepreneur,Independent professional,Stratum 5,It is not classified by the SISBEN,Three,,...,86,98,78,201,182,92,5,4,4,4
2,SB11201210005154,M,Not sure,Not sure,Independent,Home,Stratum 2,Level 2,Five,,...,18,43,22,113,113,7,1,1,1,1
3,SB11201210007504,F,Not sure,Not sure,Other occupation,Independent,Stratum 2,It is not classified by the SISBEN,Three,,...,76,80,48,137,157,67,4,3,2,2
4,SB11201210007548,M,Complete professional education,Complete professional education,Executive,Home,Stratum 4,It is not classified by the SISBEN,One,,...,98,100,71,189,198,98,5,4,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12406,SB11201420568705,M,Ninguno,Complete Secundary,Other occupation,Auxiliary or Administrative,Stratum 2,It is not classified by the SISBEN,Six,,...,86,87,65,142,176,88,5,4,2,2
12407,SB11201420573045,M,Complete professional education,Complete Secundary,Executive,Other occupation,Stratum 2,Level 2,Five,,...,44,11,0,127,107,4,1,1,4,2
12408,SB11201420578809,M,Complete technique or technology,Complete technique or technology,Retired,Home,Stratum 2,Level 2,Five,,...,90,81,87,192,188,95,5,4,2,2
12409,SB11201420578812,F,Complete professional education,Complete professional education,Independent professional,Small entrepreneur,Stratum 3,It is not classified by the SISBEN,Seven,,...,51,8,42,121,146,50,3,3,3,2
12410,SB11201420583232,M,Complete Secundary,Complete primary,Independent,Home,Stratum 3,Level 1,Four,,...,91,79,47,193,178,89,5,4,2,4

In [27]:
check = df[2].unique().tolist()
print(check)

['Incomplete Professional Education', 'Complete Secundary', 'Not sure', 'Complete professional education', 'Incomplete Secundary', 'Incomplete technical or technological', 'Complete technique or technology', 'Incomplete primary ', 'Complete primary ', 'Postgraduate education', '0', 'Ninguno']

In [29]:
check1 = df[3].unique().tolist()
print(check1)

['Complete technique or technology', 'Complete professional education', 'Not sure', 'Complete Secundary', 'Incomplete technical or technological', 'Incomplete primary ', 'Incomplete Secundary', 'Incomplete Professional Education', 'Postgraduate education', 'Complete primary ', '0', 'Ninguno']

In [30]:
check2 = df[4].unique().tolist()
print(check2)

['Technical or professional level employee', 'Entrepreneur ', 'Independent', 'Other occupation', 'Executive', 'Small entrepreneur ', 'Independent professional', 'Operator', '0', 'Retired', 'Auxiliary or Administrative', 'Home']

In [31]:
check3 = df[5].unique().tolist()
print(check3)

['Home', 'Independent professional', 'Independent', 'Executive', 'Operator', 'Entrepreneur ', 'Small entrepreneur ', 'Technical or professional level employee', '0', 'Auxiliary or Administrative', 'Other occupation', 'Retired']

In [35]:
check4 = df[7].unique().tolist()
print(check4)

['It is not classified by the SISBEN', 'Level 2', 'Level 1', 'Esta clasificada en otro Level del SISBEN', 'Level 3', '0']

In [36]:
check5 = df[8].unique().tolist()
print(check5)

['Three', 'Five', 'One', 'Four', 'Six', 'Two', 'Twelve or more', 'Nueve', 'Eight', 'Seven', 'Ten', 'Once', '0']

In [72]:
check6 = df[44].unique().tolist()
print(check6)

[2, 4, 1, 3]